// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.kakao.sdk.flutter.auth

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AuthMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PkceDto (
  val codeVerifier: String,
  val codeChallenge: String,
  val codeChallengeMethod: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PkceDto {
      val codeVerifier = pigeonVar_list[0] as String
      val codeChallenge = pigeonVar_list[1] as String
      val codeChallengeMethod = pigeonVar_list[2] as String
      return PkceDto(codeVerifier, codeChallenge, codeChallengeMethod)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      codeVerifier,
      codeChallenge,
      codeChallengeMethod,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PkceDto) {
      return false
    }
    if (this === other) {
      return true
    }
    return AuthMessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class AuthMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PkceDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PkceDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AuthHostApi {
  fun authorizeWithKakaoTalk(appKey: String, redirectUri: String, kaHeader: String, pkce: PkceDto?, nonce: String?, channelPublicIds: List<String>?, serviceTerms: List<String>?, androidTalkPackageName: String, iosLoginScheme: String, iosUniversalLink: String, callback: (Result<String>) -> Unit)
  fun authorize(url: String, redirectUri: String, callback: (Result<String>) -> Unit)
  fun launchAppsUrl(url: String, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by AuthHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AuthMessagesPigeonCodec()
    }
    /** Sets up an instance of `AuthHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AuthHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kakao_flutter_sdk_auth.AuthHostApi.authorizeWithKakaoTalk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appKeyArg = args[0] as String
            val redirectUriArg = args[1] as String
            val kaHeaderArg = args[2] as String
            val pkceArg = args[3] as PkceDto?
            val nonceArg = args[4] as String?
            val channelPublicIdsArg = args[5] as List<String>?
            val serviceTermsArg = args[6] as List<String>?
            val androidTalkPackageNameArg = args[7] as String
            val iosLoginSchemeArg = args[8] as String
            val iosUniversalLinkArg = args[9] as String
            api.authorizeWithKakaoTalk(appKeyArg, redirectUriArg, kaHeaderArg, pkceArg, nonceArg, channelPublicIdsArg, serviceTermsArg, androidTalkPackageNameArg, iosLoginSchemeArg, iosUniversalLinkArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AuthMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AuthMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kakao_flutter_sdk_auth.AuthHostApi.authorize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val redirectUriArg = args[1] as String
            api.authorize(urlArg, redirectUriArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AuthMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AuthMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.kakao_flutter_sdk_auth.AuthHostApi.launchAppsUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.launchAppsUrl(urlArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AuthMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AuthMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
