// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsAuthMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsAuthMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsAuthMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashAuthMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashAuthMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashAuthMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct PkceDto: Hashable {
  var codeVerifier: String
  var codeChallenge: String
  var codeChallengeMethod: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PkceDto? {
    let codeVerifier = pigeonVar_list[0] as! String
    let codeChallenge = pigeonVar_list[1] as! String
    let codeChallengeMethod = pigeonVar_list[2] as! String

    return PkceDto(
      codeVerifier: codeVerifier,
      codeChallenge: codeChallenge,
      codeChallengeMethod: codeChallengeMethod
    )
  }
  func toList() -> [Any?] {
    return [
      codeVerifier,
      codeChallenge,
      codeChallengeMethod,
    ]
  }
  static func == (lhs: PkceDto, rhs: PkceDto) -> Bool {
    return deepEqualsAuthMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAuthMessages(value: toList(), hasher: &hasher)
  }
}

private class AuthMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PkceDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AuthMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PkceDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AuthMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AuthMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AuthMessagesPigeonCodecWriter(data: data)
  }
}

class AuthMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AuthMessagesPigeonCodec(readerWriter: AuthMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AuthHostApi {
  func authorizeWithKakaoTalk(appKey: String, redirectUri: String, kaHeader: String, pkce: PkceDto?, nonce: String?, channelPublicIds: [String]?, serviceTerms: [String]?, androidTalkPackageName: String, iosLoginScheme: String, iosUniversalLink: String, completion: @escaping (Result<String, Error>) -> Void)
  func authorize(url: String, redirectUri: String, completion: @escaping (Result<String, Error>) -> Void)
  func launchAppsUrl(url: String, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AuthHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AuthMessagesPigeonCodec.shared }
  /// Sets up an instance of `AuthHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AuthHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let authorizeWithKakaoTalkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kakao_flutter_sdk_auth.AuthHostApi.authorizeWithKakaoTalk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeWithKakaoTalkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appKeyArg = args[0] as! String
        let redirectUriArg = args[1] as! String
        let kaHeaderArg = args[2] as! String
        let pkceArg: PkceDto? = nilOrValue(args[3])
        let nonceArg: String? = nilOrValue(args[4])
        let channelPublicIdsArg: [String]? = nilOrValue(args[5])
        let serviceTermsArg: [String]? = nilOrValue(args[6])
        let androidTalkPackageNameArg = args[7] as! String
        let iosLoginSchemeArg = args[8] as! String
        let iosUniversalLinkArg = args[9] as! String
        api.authorizeWithKakaoTalk(appKey: appKeyArg, redirectUri: redirectUriArg, kaHeader: kaHeaderArg, pkce: pkceArg, nonce: nonceArg, channelPublicIds: channelPublicIdsArg, serviceTerms: serviceTermsArg, androidTalkPackageName: androidTalkPackageNameArg, iosLoginScheme: iosLoginSchemeArg, iosUniversalLink: iosUniversalLinkArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeWithKakaoTalkChannel.setMessageHandler(nil)
    }
    let authorizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kakao_flutter_sdk_auth.AuthHostApi.authorize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let redirectUriArg = args[1] as! String
        api.authorize(url: urlArg, redirectUri: redirectUriArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeChannel.setMessageHandler(nil)
    }
    let launchAppsUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.kakao_flutter_sdk_auth.AuthHostApi.launchAppsUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchAppsUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.launchAppsUrl(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      launchAppsUrlChannel.setMessageHandler(nil)
    }
  }
}
